# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = atmega328
ARDUINO_PORT = /dev/ttyUSB1
ARDUINO_LIBS = SPI EtherSia NanodeUNIO

include /usr/share/arduino/Arduino.mk
